stages:
  - lint
  - test

variables:
  NODE_IMAGE: node:20-alpine

frontend_format:
  stage: lint
  image: $NODE_IMAGE
  before_script:
    - apk add --no-cache git
  script:
    - cd app
    - npm ci
    - npm run format
    - git config --global user.email "mr.robot@example.com"
    - git config --global user.name "Mr. Robot"
    - git remote set-url origin https://oauth2:${LINT_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git
    - git add .
    - git diff-index --quiet HEAD || git commit -m "Apply Prettier formatting"
    - git push origin HEAD:$CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - app/
    expire_in: 1 hour
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

frontend_lint:
  stage: lint
  needs:
    - job: frontend_format
      artifacts: true
  image: $NODE_IMAGE
  script:
    - cd app
    - npm run lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

frontend_test:
  stage: test
  needs:
    - job: frontend_format
      artifacts: true
  image: trion/ng-cli-karma:latest
  script:
    - cd app
    - ng test --watch=false
  artifacts:
    when: always
    paths:
      - app/test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'